### PR TITLE
Added minified version for all cultures; Changed de-DE currency symbol 

### PR DESCRIPTION
**Pull request by frankiDotNet**
- Changed 'de-CH' currency symbol to 'CHF'
- Added minified version for all cultures

### CODE REVIEW

**Review by thorn0 — CHANGES_REQUESTED** [review]
Committing minified files is a bad practice. I'm okay with having such a file in the package, but not in the repo. Please instead of this file, commit a change to gruntfile so that when we run `grunt build`, this file will be built too. Also, please note that every culture file has its own copy of the UMD boilerplate code whereas in the combined file only one copy of it would suffice:

```js
;(function (global, factory) {
   typeof exports === 'object' && typeof module !== 'undefined'
       && typeof require === 'function' ? factory(require('../sffjs')) :
   typeof define === 'function' && define.amd ? define(['../sffjs'], factory) :
   factory(global.sffjs)
}(this, function (sffjs) { 'use strict';
    sffjs.registerCulture({ ... });
    sffjs.registerCulture({ ... });
    // ...
}));
```

**Comment by frankiDotNet** [comment]
I am not familiar with grunt build process. I would take care of this, but to stay generic all files should be untouched and the build task should extract the `sffjs.registerCulture` part concat all of them into the above written fuction that you described. That right ?

**Comment by thorn0** [comment]
Right. I'm going to merge the CHF change now. Please submit a separate PR for that combined culture file.

BTW, overall, it's not a good idea to mix multiple unrelated changes in one PR. It's always better to submit separate PRs in such a situation.

**Comment by frankiDotNet** [comment]
Thanks! I will take care next time..

**Pull request merged**
